name: pose_estimation
channels:
    - anaconda
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - torch
    - torchvision
    - numpy
    - matplotlib
    - seaborn
    - pandas
    - opencv
    - cudatoolkit
    - pip:
        - mxnet-cu102
        - gluoncv
        - cython
        - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
        - git+https://github.com/facebookresearch/detectron2.git
