name: pose_estimation
channels:
    - anaconda
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - python
    - pip
    - pytorch=1.5
    - torchvision=0.6
    - numpy
    - matplotlib
    - seaborn
    - pandas
    - opencv
    - cudatoolkit=10.1
    - pycocotools
    - pyyaml=5.1
    - pip:
        - mxnet-cu101
        - gluoncv
        - cython
