name: pose_estimation
channels:
    - anaconda
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - python=3.6
    - pip
    - pytorch>=1.4
    - torchvision>=0.3.0
    - numpy
    - matplotlib
    - seaborn
    - pandas
    - opencv
    - cudatoolkit=10.1
    - pycocotools
    - pip:
        - mxnet-cu101
        - gluoncv
        - cython
